services:
  postgres:
    image: "postgres:12-alpine"
    volumes:
      - paytacamap_db:/var/lib/postgresql/data
    env_file:
      - .env_prod
    expose:
      - "5432"
  paytacamap:
    build: /root/paytaca-map
    command: [ "supervisord", "-c", "/code/supervisord.conf", "--nodaemon" ]
    ports:
      - "8000:8000"
      - "9000:9000"
    env_file:
      - .env_prod
    volumes:
      - /var/www/paytaca-map/static:/code/static
      - /var/www/paytaca-map/media:/code/media
    depends_on:
      - postgres
volumes:
  paytacamap_db:
    external: true
